[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"
