[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle Next.js routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle Next.js public files
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/functions/next"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
