[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle root domain
[[redirects]]
  from = "/"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Handle Next.js public files
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle Shopify CDN images
[[redirects]]
  from = "https://cdn.shopify.com/*"
  to = "https://cdn.shopify.com/:splat"
  status = 200
  force = true

# Handle Shopify subdomain CDN images
[[redirects]]
  from = "https://*.cdn.shopify.com/*"
  to = "https://:subdomain.cdn.shopify.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
