[build]
  publish = ".next"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200