[build]
  command = "yarn build"
  publish = ".next/standalone/.next"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_PUBLIC_AVAILABLE_FOR_PREVIEW = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_RUNTIME = "edge"
  NEXT_STANDALONE = "true"

[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_RUNTIME = "edge"
  NEXT_STANDALONE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Handle Next.js data files
[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle Next.js public files
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

# Handle dynamic routes first
[[redirects]]
  from = "/products/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

# Handle Shopify CDN images
[[redirects]]
  from = "https://cdn.shopify.com/*"
  to = "https://cdn.shopify.com/:splat"
  status = 200
  force = true

# Handle Shopify subdomain CDN images
[[redirects]]
  from = "https://*.cdn.shopify.com/*"
  to = "https://:subdomain.cdn.shopify.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
