[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all routes to Next.js handler
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true
